### ISSUE TITLE
Tactsuit 16

### ISSUE THREAD

**Issue by foxora** [HerpDerpinstine/bHapticsOSC#9]
Can a option be added for the Tactsuit x16 that would use fewer contact points on the avatar?

**Comment by HerpDerpinstine** [comment]
If someone wants to make a model for the x16 then I suppose it could be easily added.
I am horrible at modelling or else bHapticsOSC would already have had one.

The bHaptics Player will handle the interaction anyways if you use an x16 vest with x40 integration.
bHaptics made it so that even if something is designed with the x40 in mind that an x16 will still work with it.

**Comment by foxora** [comment]
I was able to remove unused contact points and just expand them a bit:
![image](https://user-images.githubusercontent.com/22553183/195526881-7d016e4e-0a62-4447-b1a1-154ed6185af0.png)

also I removed animation layers not in use 5,6,7,8:
![image](https://user-images.githubusercontent.com/22553183/195527366-13968fa0-56e0-4dea-b28b-c1b2ad54b9f4.png)

I don't really want to use a mesh and the script works great, thanks for the hard work!
